package tech.illusion.spacecube.content

import android.util.Log
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalDensity
import com.pico.spatial.core.ecs.CollisionComponent
import com.pico.spatial.core.ecs.Entity
import com.pico.spatial.core.ecs.InteractableComponent
import com.pico.spatial.core.ecs.ModelEntity
import com.pico.spatial.core.ecs.resource.BlendingMode
import com.pico.spatial.core.ecs.resource.MeshResource
import com.pico.spatial.core.ecs.resource.PhysicsMaterialResource
import com.pico.spatial.core.ecs.resource.ShapeResource
import com.pico.spatial.core.ecs.resource.UnlitMaterial
import com.pico.spatial.core.math.Color4
import com.pico.spatial.core.math.Vector3
import com.pico.spatial.ui.foundation.gesture.TargetEntity
import com.pico.spatial.ui.foundation.gesture.detectSpatialDragGesture
import com.pico.spatial.ui.foundation.gesture.detectTapGestures
import com.pico.spatial.ui.platform.LengthUnit
import com.pico.spatial.ui.platform.LocalPhysicalLengthConverter
import kotlin.math.PI
import kotlin.math.abs
import kotlin.math.cos
import tech.illusion.spacecube.game.GameEngine
import tech.illusion.spacecube.game.NO_PIECE_ID

/**
 * V2 control scheme: a translucent glass plane behind the playfield, driven by the
 * SDK's own spatial gesture detectors, as an A/B comparison against V1 (which polls
 * HandTrackingProvider and derives everything itself).
 *
 * Covers horizontal movement, downward soft drop, and double-tap rotation. (Down was
 * added 2026-08-07 after the user found dragging down did nothing - the original
 * request only named left/right and double-tap.)
 *
 * ## Why an earlier attempt at this produced total silence
 *
 * A previous version put these detectors inside an `AttachmentPanel`. That cannot
 * work, for two structural reasons that have nothing to do with the API being used
 * wrongly:
 * 1. An AttachmentPanel's Compose content is hosted in its own separate view host,
 *    so it never receives the MotionEvent generated by a ray hit on a 3D entity
 *    living in the `SpatialView`.
 * 2. `TargetEntity.hit(someEntity)` could never match a hit delivered against the
 *    panel itself.
 *
 * So these modifiers go on the **`SpatialView`** - the view that actually hosts the
 * 3D content and, per its own KDoc, "can be used to receive users input". Never on
 * a panel. That was almost certainly the original bug, and the stale-firmware
 * theory was probably a red herring.
 *
 * ## Diagnostics
 *
 * [UNTARGETED_DRAG_PROBE] can drop the drag detector's `targetedToEntity` so it
 * reports whatever it hits, which distinguishes "no events arrive at all" from "the
 * platform's entity verifier rejected them". It is OFF by default because an
 * untargeted detector on the `SpatialView` swallows the panel buttons' input too.
 *
 * Watch app tag [V2_LOG_TAG] alongside the SDK's own internal tag
 * `SUISpatialGesture` - the latter only appears because AndroidManifest.xml now sets
 * `pico.spatial.ui.Logger`, without which the SDK discards even its own errors.
 */
internal const val V2_LOG_TAG = "SpaceCubeV2Gesture"

/**
 * Diagnostic only: bypass `targetedToEntity` on the drag detector and range-check
 * the reported entity in the callback instead, to see whether events arrive at all
 * when the platform's entity verifier is the suspect.
 *
 * **Leave this false in normal use.** An untargeted detector on the `SpatialView`
 * accepts a pointer-down anywhere in the Stage and starts a gesture, which STARVES
 * the AttachmentPanel buttons - that is exactly what caused the user's report that
 * "切换到V2手势后，点击主面板UI上的按钮没有反应". Turn it on only to answer "do callbacks
 * fire at all", and expect the UI to be unusable while it is on.
 */
private const val UNTARGETED_DRAG_PROBE = false

// The plane stands at the base plate's FAR edge, backing the playfield from behind -
// matching the original spec ("在游戏井背面...覆盖背面板"). It briefly went to the NEAR
// edge on a misread red-arrow annotation; the user's correction was "玻璃放置位置反了，
// 放到了用户这一侧". Stage's +Z points at the user, so behind is negative Z.
private const val V2_PLANE_THICKNESS_M = 0.006f

// Requested opacity for the glass surface ("不透明度为0.2的玻璃材质平面").
private const val V2_PLANE_OPACITY = 0.2f

// V2 movement speed relative to 1:1 pointer tracking, where 1.0 means one rendered
// cell of drag moves the piece exactly one cell. Set to 2/3 per user request
// ("通过V2手势的操作，移动速度应该为当前的2/3").
//
// Expressed as a SPEED and divided into pixelsPerColumn below, rather than as a
// multiplier on the distance: speed and distance-per-cell are inverses, so writing
// it the other way round invites getting the direction backwards. Two-thirds speed
// means each cell costs 1.5x the drag.
private const val V2_MOVE_SPEED_FACTOR = 2f / 3f
private val V2_PLANE_COLOR = Color4(1f, 1f, 1f, 0.001f)

/**
 * The interactable glass plane covering the back of the well.
 *
 * Carries [InteractableComponent] + [CollisionComponent]: those are the documented
 * prerequisites for receiving user gesture input, and a mesh alone receives nothing.
 * Note it starts `enabled = true` unlike the pooled board cubes - a disabled entity
 * may be excluded from hit-testing entirely.
 */
internal fun createV2ControlPlane(spanX: Float, spanY: Float): ModelEntity {
    val size = Vector3(spanX * 2, spanY * 2, V2_PLANE_THICKNESS_M)
    val mesh = MeshResource.createBox(size, cornerRadius = 0.1f)
    val material = UnlitMaterial.create(BlendingMode.TRANSPARENT).apply {
        setBaseColor(V2_PLANE_COLOR)
        setOpacity(V2_PLANE_OPACITY)
    }
    return ModelEntity(mesh, material).apply {
        components.set(InteractableComponent())
        components.set(
            CollisionComponent(
                collisionShape = listOf(ShapeResource.createBox(size)),
                physicsMaterial = PhysicsMaterialResource(),
            )
        )
    }
}

/**
 * Where to put the plane relative to the anchor: vertically centred on the
 * playfield, standing at the base plate's far edge (behind the board).
 */
internal fun v2ControlPlanePosition(boardCenterY: Float, plateFarEdgeZ: Float): Vector3 =
    Vector3(0f, boardCenterY, plateFarEdgeZ)

/**
 * Builds the gesture [Modifier] for V2. **Apply this to the `SpatialView`**, not to
 * any AttachmentPanel - see the file KDoc for why that distinction is the whole
 * ballgame.
 *
 * Each detector gets its own `pointerInput` block: every `detectSpatial*` body is a
 * single `awaitEachGesture` that never returns, so a second detector in the same
 * block would be unreachable.
 */
@Composable
internal fun v2GestureModifier(
    engine: GameEngine,
    controlPlane: Entity,
    cellStepMeters: Float,
    sceneScale: Float,
    sceneYawDegrees: Float,
    active: Boolean,
): Modifier {
    val context = LocalContext.current
    val density = LocalDensity.current

    // dragAmount.x is in the SpatialView's (screen) coordinate system, NOT the
    // control plane's local space - confirmed both on-device (AGENTS.md "Known
    // unfixed") and by the SDK's own docs (implement-basic-interactions-for-3d-
    // objects.md: "dragAmount follows Compose View's coordinate system"), which is
    // exactly why it never rotates with the plane/anchor. A screen-space
    // horizontal drag corresponds to a fixed real-world direction (approximately
    // world +X, assuming the user is roughly facing the board - there is no head
    // orientation data available here to do better). Once the anchor is yawed by
    // sceneYawDegrees, the board's own local X axis is that many degrees away
    // from world X, so only the world-X component that actually projects onto
    // board-X should count; the rest is lost off-axis (there is no world-Z data in
    // a 2D screen delta to recover via the fuller toBoardSpaceDelta rotation used
    // by V1). That projection is exactly cos(yaw). yaw = 0 (the common case,
    // scene never rotated) leaves this at 1 - a no-op.
    val yawCorrection = remember(sceneYawDegrees) {
        cos((sceneYawDegrees * PI / 180.0).toFloat())
    }

    // The SDK's own metres->pixels factor (the same one AttachmentPanelComponent
    // uses), so "one rendered cell of drag = one column" holds without a magic
    // constant. Guarded: this CompositionLocal is documented to throw when absent,
    // and its availability inside a Stage was never confirmed.
    val pixelsPerColumn = run {
        val converter = runCatching { LocalPhysicalLengthConverter.current }.getOrNull()
        remember(converter, density, cellStepMeters, sceneScale) {
            if (converter == null) {
                Log.w(V2_LOG_TAG, "LocalPhysicalLengthConverter unavailable - falling back to density only")
                (cellStepMeters * sceneScale * density.density * 160f / V2_MOVE_SPEED_FACTOR).coerceAtLeast(1f)
            } else {
                val pixelsPerMeter = with(density) { converter.lengthToDp(1f, LengthUnit.Meters).toPx() }
                // A value near 1.0 means off-platform identity stubs, not a real scale.
                Log.i(V2_LOG_TAG, "pixelsPerMeter=${"%.1f".format(pixelsPerMeter)} (expect hundreds-to-thousands)")
                (cellStepMeters * sceneScale * pixelsPerMeter / V2_MOVE_SPEED_FACTOR).coerceAtLeast(1f)
            }
        }
    }

    val dragState = remember { V2DragState() }

    return Modifier
        .pointerInput(active, engine, controlPlane, pixelsPerColumn, yawCorrection) {
            if (!active) return@pointerInput
            while (true) {
                detectSpatialDragGesture(
                    context = context,
                    // Deliberately untargeted while probing - see UNTARGETED_DRAG_PROBE.
                    targetedToEntity = if (UNTARGETED_DRAG_PROBE) null else TargetEntity.hit(controlPlane),
                    onDragStart = { _, _ ->
                        dragState.reset()
                        dragState.pieceId = engine.pieceId
                        Log.i(
                            V2_LOG_TAG,
                            "drag START pixelsPerColumn=${"%.1f".format(pixelsPerColumn)} pieceId=${dragState.pieceId}",
                        )
                    },
                    onDragEnd = {
                        Log.i(V2_LOG_TAG, "drag END after ${dragState.callbackCount} callbacks")
                        dragState.reset()
                    },
                    onDragCancel = {
                        Log.i(V2_LOG_TAG, "drag CANCEL after ${dragState.callbackCount} callbacks")
                        dragState.reset()
                    },
                ) { value ->
                    dragState.callbackCount++
                    val onOurPlane = value.targetEntity == controlPlane
                    if (UNTARGETED_DRAG_PROBE && !onOurPlane) {
                        // The single most informative line if V2 misbehaves: says
                        // whether events arrive at all and what they actually hit.
                        Log.i(
                            V2_LOG_TAG,
                            "drag #${dragState.callbackCount} IGNORED - hit ${value.targetEntity} not the control plane",
                        )
                        return@detectSpatialDragGesture
                    }

                    // A drag only ever steers the piece it began on. If that piece
                    // locked mid-drag, the session is spent: the user has to lift and
                    // start a new drag rather than have leftover travel shove the
                    // freshly spawned piece sideways. Latched, so it stays dead for the
                    // rest of the session instead of resuming on the piece after next.
                    if (dragState.pieceId == NO_PIECE_ID) {
                        // Defensive: some detector paths could deliver a move without a
                        // preceding onDragStart. Adopt the current piece rather than
                        // comparing against a bogus id and killing a legitimate drag.
                        dragState.pieceId = engine.pieceId
                    }
                    if (dragState.pieceId != engine.pieceId) {
                        if (!dragState.staleLogged) {
                            dragState.staleLogged = true
                            Log.i(
                                V2_LOG_TAG,
                                "drag #${dragState.callbackCount} STALE - started on piece ${dragState.pieceId}, " +
                                    "now ${engine.pieceId}; ignoring until the next drag",
                            )
                        }
                        return@detectSpatialDragGesture
                    }

                    // Project the screen-space delta onto the board's own X axis
                    // before accumulating - see yawCorrection's KDoc above.
                    val stepX = value.dragAmount.x * yawCorrection
                    val stepY = value.dragAmount.y
                    dragState.accumulatedX += stepX
                    // View-space +Y points DOWN while 3D +Y points up, so a downward
                    // drag arrives as POSITIVE y - which is the direction we want for
                    // dropping. (That inversion is exactly why the SDK's own
                    // metres->pixels mapping negates Y.)
                    dragState.accumulatedY += stepY

                    // Horizontal. Truncate toward zero: symmetric left/right, and it
                    // demands a full cell of travel per step so there's no boundary
                    // double-fire.
                    val wantX = (dragState.accumulatedX / pixelsPerColumn).toInt()
                    var appliedX = 0
                    repeat(abs(wantX)) {
                        val accepted = if (wantX > 0) engine.moveRight() else engine.moveLeft()
                        if (!accepted) return@repeat
                        appliedX++
                    }
                    if (appliedX > 0) {
                        // Consume only what landed and keep the sub-cell remainder, so
                        // a slow drag steps evenly instead of stalling then jumping.
                        dragState.accumulatedX -= appliedX * pixelsPerColumn * (if (wantX > 0) 1f else -1f)
                    }

                    // Vertical: soft drop. Only downward does anything - a piece can't
                    // move up - so upward travel is clamped away rather than banked,
                    // otherwise dragging up would build credit that silently cancels a
                    // later genuine downward drag. Unlike V1 this can safely be
                    // incremental: each cell of travel issues one EXTRA moveDown() on
                    // top of gravity, rather than trying to place the piece at an
                    // absolute row (which gravity would invalidate).
                    if (dragState.accumulatedY < 0f) dragState.accumulatedY = 0f
                    val wantY = (dragState.accumulatedY / pixelsPerColumn).toInt()
                    var appliedY = 0
                    repeat(wantY) {
                        if (!engine.moveDown()) return@repeat
                        appliedY++
                    }
                    if (appliedY > 0) dragState.accumulatedY -= appliedY * pixelsPerColumn

                    Log.i(
                        V2_LOG_TAG,
                        "drag #${dragState.callbackCount} stepPx=(${"%.2f".format(stepX)}, ${"%.2f".format(stepY)}) " +
                            "accPx=(${"%.2f".format(dragState.accumulatedX)}, ${"%.2f".format(dragState.accumulatedY)}) " +
                            "wantXY=($wantX,$wantY) appliedXY=($appliedX,$appliedY) kind=${value.interactionKind} " +
                            "yawDeg=${"%.1f".format(sceneYawDegrees)} yawCorr=${"%.2f".format(yawCorrection)}",
                    )
                }
            }
        }
        .pointerInput(active, engine, controlPlane) {
            if (!active) return@pointerInput
            // NOT detectSpatialTapGesture: it has no double-tap at all, and it only
            // fires when the platform reports GestureState.TAP. This is PICO's
            // entity-scoped fork of the Compose detector - real onDoubleTap, and its
            // success check is plain Compose down/up logic. Named args are mandatory:
            // androidx.compose.foundation.gestures has a same-named function and only
            // the leading `context` distinguishes them.
            detectTapGestures(
                context = context,
                targetedToEntity = TargetEntity.hit(controlPlane),
                onDoubleTap = {
                    val rotated = engine.rotateClockwise()
                    Log.i(V2_LOG_TAG, "double tap -> rotateClockwise() = $rotated")
                },
                onTap = { Log.i(V2_LOG_TAG, "single tap on plane (double-tap to rotate)") },
            )
        }
}

/** Mutable scratch state for one V2 drag session. */
private class V2DragState {
    var accumulatedX = 0f
    var accumulatedY = 0f
    var callbackCount = 0

    /** `GameEngine.pieceId` this drag began on; the session dies when it changes. */
    var pieceId = NO_PIECE_ID
    var staleLogged = false

    fun reset() {
        accumulatedX = 0f
        accumulatedY = 0f
        callbackCount = 0
        pieceId = NO_PIECE_ID
        staleLogged = false
    }
}
